Refactor Pull Request
Star-Academy/Team2-Codes pull request #1
Opened 2020-08-03 07:08 UTC by titansarus

2020-08-03 08:31 UTC, Danyal0096 reviewed
اضافه کردن کوئری پراسسور خیلی به جا بود و در کل کدتون خوانا و خوب بود فقط بعضی جاها برای بعضی متد های پیچیده بهتره کامنت بزارید که برای فهمش نخوایم بریم ریز کد رو بخونیم که داره چه اتفاقی میافته غیر از این در کل به نظر من خوب بود

2020-08-03 09:02 UTC, mahdimalverdi requested changes

2020-08-03 09:02 UTC, mahdimalverdi commented on FullTextSearch/src/QueryProcessor.java
> +                    switch (operationType) {
همیشه Switch Case رو درون یه تابع جدا پیاده سازی کنید

2020-08-03 09:02 UTC, mahdimalverdi commented on FullTextSearch/src/QueryProcessor.java
> +        result = operationPerformerOnSet(result, subtractStrings, SetOperationType.SUBTRACT);
بهتر است این سه خط به یه تابع دیگه منتقل شود تا خوانایی کد بیشتر شود

2020-08-03 09:30 UTC, ahmadsalimi commented on FullTextSearch/src/Document.java
> +                document = doc;
<div dir="rtl">

اینجا بنظرم نیازی نیست یه متغیر به اسم document تعریف بشه و بعدا return بشه. همینجا return بشه و پایین حلقه هم return null بشه بهتره. علاوه بر اون مشکلی که این کد داره اینه که اگه ۱۰۰۰۰۰۰۰ تا داکیومنت داشته باشیم و تو اولیش همونی که میخوایم پیدا شه، بازم حلقه ۱۰۰۰۰۰۰۰ بار انجام میشه در حالی که وقتی پیدا شد نباید ادامه داد.

</div>

2020-08-03 09:30 UTC, ahmadsalimi commented on FullTextSearch/src/QueryProcessor.java
> +    private Set<String> operationPerformerOnSet(final Set<String> base, final List<String> queryWords,
<div dir="rtl">

این تابع بهتره براش کلاس جداگونه بنویسید و برای عملیات مختلف مثل and و or و ... از polymorphism استفاده کنید، به جای این که از switch case استفاده کنید. مثلا یک کلاس abstract داشته باشید که تابع اصلیش مشترک باشه، ولی یک تابع protected توشون abstract باشه و نوع عملیات رو تعیین کنه (مثلا اینجا برای or تابع addAll، برای and تابع retainAll و... صرفا تفاوت داره)

در مورد switch case code smell هم [این لینک](https://www.c-sharpcorner.com/article/switch-statement-a-code-smell/) رو یه نگاهی بندازین.

</div>

2020-08-03 09:41 UTC, MahdiHma commented on FullTextSearch/src/FileReader.java
فکر میکنم این قسمت از کد شما کمی پیچیدگی دارد. با اضافه کردن کامنت و البته کم کردن پیچیدگی برخی توابع می‌توان مشکل آن را 
 برطرف کرد. برای مثال می‌شد هر کلمه از فایل را به ترتیب خوانده و به لیستمان اضافه کنیم تا آنکه همه‌ی کلمات را داخل یک رشته بریزیم و توسط تابع دیگری آن را تبدیل به کلمات کنیم.

2020-08-03 09:42 UTC, MahdiHma reviewed
کد تمیز و خوانا می‌باشد و نام‌گذاری ها درست. برخی قسمت‌ها به درستی کامنت گذاری شده اند. موفق باشید.

2020-08-03 09:48 UTC, alrz1999 commented on FullTextSearch/src/Document.java
> +        final StringTokenizer stringTokenizer = new StringTokenizer(getContent(), " ,.;-'()\"@[]><");
بهتره دلیمتر ها رو کانست استاتیک تعریف کنید

2020-08-03 09:49 UTC, alrz1999 commented on FullTextSearch/src/Document.java
>      public void tokenizeContent() {
فکر کنم این تابع ربطی به داکیومنت نداره و بهتره یه کلاس برای 
Tokenize
کردن ایجاد کنین تا اگه فرایند ایجاد توکن عوض شد این کلاس تغییر نکنه

2020-08-03 09:50 UTC, titansarus commented on FullTextSearch/src/Document.java
> +                document = doc;
ریترن رو من یک افزونه ای به اسم
PMD
نصب کردم که براساس یکسری قوانین شرکت های بزرگ برای کد جاوا میاد کد رو چک می کنه و نوشته بود که بهتره یک کد تا جایی که ممکنه یک ریترن داشته باشه.  ولی اون 1000 بار حق با توعه و فکر کنم با
break
هندلش کنم که این قانونه هم رعایت بشه، اوکی میشه. ممنون.

2020-08-03 09:51 UTC, alrz1999 commented on FullTextSearch/src/Document.java
> +    public static void tokenizeAllDocuments(final List<Document> documents) {
همینطور این تابع

2020-08-03 09:56 UTC, titansarus commented on FullTextSearch/src/FileReader.java
دلیل این که کل متن رو می خونیم، این بوده که برای تست کردن و این که ببینیم آیا واقعا داریم درست عمل می کنیم، به کل متن داک با همون ترتیبی که بوده دسترسی داشته باشیم و بعد از اون جایی که برای پرفرمنس، خود کلمات دارن در سِت ذخیره می شن، امکان ذخیره کل داک در ست با همان ترتیب و تکرار کلمات موجود نبوده. برای همین این روش رو اعمال کردیم. پیچیدگیش رو بررسی می کنم که تا جایی که بشه، ساده تر بکنیمش.
ممنون.

2020-08-03 10:13 UTC, alrz1999 requested changes

2020-08-03 10:13 UTC, alrz1999 commented on FullTextSearch/src/FileReader.java
>              listAllFilesInFolder();
دلیل خاصی داشتین که این تابع اینجا فراخوانی شده نه تو کانستراکتور؟

2020-08-03 10:13 UTC, alrz1999 commented on FullTextSearch/src/FileReader.java
> +    public List<Document> createDocumentFromFolder() {
بهتر نیست اسم این تابع 
getDocuments
باشه ؟

2020-08-03 10:13 UTC, alrz1999 commented on FullTextSearch/src/FileReader.java
> -    public String readOneFile(String address) {
توابعی مثل این تابع که فقط داخل خود کلاس استفاده میشن بهتره
private 
باشن

2020-08-03 10:13 UTC, alrz1999 commented on FullTextSearch/src/InputProcessor.java
> +        final List<String> and = extractAllQueryWords(getInputString());
inputString 
داخل کلاس هست و احتیاجی نیست به عنوان آرگومان تابع پاس داده بشه

2020-08-03 10:13 UTC, alrz1999 commented on FullTextSearch/src/InputProcessor.java
> +    public static List<String> wordExtarctor(final Matcher matcher) {
کلا تا جایی که میتونین تابع استاتیک کمتر تعریف کنین
اینجا استاتیک بودن تابع هیچ پوینتی نداره

2020-08-03 10:13 UTC, alrz1999 commented on FullTextSearch/src/InputProcessor.java
> +    public static List<String> extractAllQueryWords(final String input) {
همینطور اینجا . دو تای پایینی

2020-08-03 10:29 UTC, titansarus commented on FullTextSearch/src/FileReader.java
>              listAllFilesInFolder();
دلیلش این بوده که اگه چند تا پوشه داشته باشیم، بشه با یک
FileReader
و تغییر آدرسش همه پوشه ها رو خوند. ولی الآن که فکر می کنم، می بینم منطقی تره در کانستراکتور فراخوانی کنیم و در حالتی که چند تا پوشه بود هم چند تا
FileReader بذاریم.

2020-08-03 10:33 UTC, titansarus commented on FullTextSearch/src/FileReader.java
> +    public List<Document> createDocumentFromFolder() {
اوکی می کنمش. همین طور بقیه نکاتی که گفتی رو.

2020-08-03 11:22 UTC, kimianoorbakhsh reviewed
کلا خیلی کد خوانا و خوبی زدید ، چند نکته بود که تو ریویو های بچه ها اومده بود منم تایید کردم.

2020-08-03 11:36 UTC, titansarus commented on FullTextSearch/src/QueryProcessor.java
> +                    switch (operationType) {
این رو اول تابع کردیم، بعد با توجه به پیشنهاد احمد، کلاس
SetOperator
زدیم که
Abstract
عه و سه تا کلاس دیگه ازش ارث بری می کنن و با کمک
Polymorphism
هندل کردیمش.

2020-08-03 11:37 UTC, titansarus commented on FullTextSearch/src/QueryProcessor.java
> +    private Set<String> operationPerformerOnSet(final Set<String> base, final List<String> queryWords,
همین کاری که گفتی رو انجام دادیم. ممنون.

2020-08-03 11:37 UTC, titansarus commented on FullTextSearch/src/Document.java
> +        final StringTokenizer stringTokenizer = new StringTokenizer(getContent(), " ,.;-'()\"@[]><");
اوکی شد در کلاس Tokenizer که جدید ساختیم.

2020-08-03 11:38 UTC, titansarus commented on FullTextSearch/src/Document.java
>      public void tokenizeContent() {
کلاس Tokenizer ایجاد کردیم.

2020-08-03 11:38 UTC, titansarus commented on FullTextSearch/src/InputProcessor.java
> +        final List<String> and = extractAllQueryWords(getInputString());
اوکی شد.

2020-08-03 11:39 UTC, titansarus commented on FullTextSearch/src/InputProcessor.java
> +    public static List<String> wordExtarctor(final Matcher matcher) {
اوکی شد.

2020-08-03 11:39 UTC, titansarus commented on FullTextSearch/src/FileReader.java
> -    public String readOneFile(String address) {
اوکی شد.

2020-08-03 13:21 UTC, ahmadsalimi commented on FullTextSearch/src/Document.java
> +                document = doc;
<div dir="rtl">

چیزی که من گفتم طبق [این لینک](https://refactoring.guru/replace-nested-conditional-with-guard-clauses) بود، هر چند تو این مورد شما خیلی guard clause سنگینی نمیشه.

</div>

2020-08-03 14:19 UTC, titansarus commented on FullTextSearch/src/Document.java
> +                document = doc;
آره فهمیدم منظورتو. این چیزی هم که میگم، برای همین حالت های کوچیک که بدون 
return
میشه معقول درشون آورد نوشته بود که سعی کنین یک ریترن آخر تابع بیش تر نداشته باشید. اون حالتی که میگی، ایف و الس تو در تو زیاد داره و مشکل ساز میشه.
در کل ممنون.

2020-08-03 20:23 UTC, AlirezaT99 approved these changes
غیر از غلط املایی تو اسم متد ابسترکت همه چی عالیه =))  موفق باشید

2020-08-03 20:29 UTC, MJSahebnasi approved these changes

2020-08-03 20:29 UTC, MJSahebnasi commented on FullTextSearch/src/Main.java
>          while (true) {
فقط در حدی که 
scanner.hasNextLine()
شکیل تره

2020-08-03 20:57 UTC, mahdimalverdi approved these changes

2020-08-04 05:45 UTC, FarshidNooshi approved these changes
خسته نباشید بابت پیاده سازی 
نامگذاری ها مناسب بودن و همینطور استفاده ی خوبی از ارث بری شده بود.

2020-08-04 06:17 UTC, alrz1999 requested changes
به نظرم یه پوشه بندی هم بکنین خیلی خوب میشه

2020-08-04 06:17 UTC, alrz1999 commented on FullTextSearch/src/Main.java
>      public static void main(String[] args) {
اینجا به نظرم اگه کارای  پیش پردازش و پردازش کوئری کاربر و نمایش نتیجه جدا بشن قشنگ تر میشه
و اینکه واسه نمایش نتیجه هم یه کلاس جدا بزارین که مثلا اگه قرار بود بعدا به جای کنسول نتیجه رو یه جور دیگه نمایش داد این کلاس تغییری نکنه

2020-08-04 06:55 UTC, Danyal0096 approved these changes

2020-08-04 07:04 UTC, titansarus commented on FullTextSearch/src/Main.java
>      public static void main(String[] args) {
ایرادایی که گفتی رو حل کردم. پوشه بندی و ساخت پکیج رو هم اوکی کردم.

2020-08-04 07:20 UTC, alrz1999 approved these changes

2020-08-04 07:21 UTC, merged