Feature/unit testing
Star-Academy/Team2-Codes pull request #2
Opened 2020-08-05 14:39 UTC by MJavadHzr

#### Phase3--Unit Testing

2020-08-06 10:41 UTC, MJSahebnasi approved these changes
موردی به نظرم نرسید
خسته نباشید

2020-08-06 10:49 UTC, AlirezaT99 approved these changes
بسیار عالی.. خسته نباشید آقایون

2020-08-08 13:23 UTC, alrz1999 requested changes

2020-08-08 13:23 UTC, alrz1999 commented on FullTextSearch/src/test/java/Model/InvertedIndexTest.java
> +        InvertedIndex invertedIndex = new InvertedIndex();
شاید اگه اینو به 
Initialize
اضافه کنین بهتر باشه

2020-08-08 13:23 UTC, alrz1999 commented on FullTextSearch/src/test/java/Utility/QueryProcessorTest.java
> +        List<Document> documents = fileReader.getDocuments();
به نظرم 
SmallEnglishData
رو فقط برا تست 
FileReader
استفاده کنین بهتره و اینجا خود داکیومنت ها را رو تو کد بزارین بهتر باشه تا تست 
QueryProcessor
به 
FileReader
وابسته نشه

2020-08-09 07:03 UTC, mahdimalverdi approved these changes

2020-08-09 08:04 UTC, MJavadHzr commented on FullTextSearch/src/test/java/Utility/QueryProcessorTest.java
> +        List<Document> documents = fileReader.getDocuments();
fixed

2020-08-09 08:09 UTC, alrz1999 approved these changes

2020-08-09 08:16 UTC, merged