Phase04
Star-Academy/Team2-Codes pull request #3
Opened 2020-08-10 09:09 UTC by MJavadHzr

### Student Grades & Average Project

2020-08-10 20:15 UTC, mahdimalverdi requested changes

2020-08-10 20:15 UTC, mahdimalverdi commented on Phase04/StudentAndScore/StudentAndScore/StudentAndScore/Program.cs
> +            var bestStudentsWithAverages =
چرا تمام این خط درون همون کلاس نرفته؟
تابع Paginate کلا پرایوت بشه نیاز نیس از بیرون بهش دسترسی باشه

2020-08-10 20:15 UTC, mahdimalverdi commented on Phase04/StudentAndScore/StudentAndScore/StudentAndScore/Utility/Query/QueryManager.cs
> +        public List<T> Paginate<T>(IEnumerable<T> linqQueryEnumerable, int numberToTake = -1)
پرایوت بشه کلا! نیازی به دسترسیش از بیرون نیس!

2020-08-10 21:12 UTC, titansarus commented on Phase04/StudentAndScore/StudentAndScore/StudentAndScore/Utility/Query/QueryManager.cs
> +        public List<T> Paginate<T>(IEnumerable<T> linqQueryEnumerable, int numberToTake = -1)
اوکی شد.

2020-08-11 04:44 UTC, Danyal0096 approved these changes
تو کلاس پوینتتون یه کانستراکتور خالی دارید باید حذف شه و نکته دیگه ای به نظرم نمیرسه و از استفاده از لامبدا اکسپرشنتون تو گروپ جوین لذت بردم ممنون:) ونهایتا موفق باشید

2020-08-11 08:31 UTC, MJSahebnasi approved these changes

2020-08-11 12:55 UTC, alrz1999 approved these changes

2020-08-11 13:31 UTC, AlirezaT99 approved these changes

2020-08-11 18:03 UTC, mahlashrifi approved these changes
<div dir="rtl">

خیلی خوب بود . مخصوصا پوشه بندی ها و همینطور interface بودن Reader . 

</div>

2020-08-11 18:07 UTC, mahlashrifi commented on Phase04/StudentAndScore/StudentAndScore/StudentAndScore/Utility/Query/QueryManager.cs
>              if (numberToTake != -1)
<div dir="rtl">

numberToTake رو متوجه نشدم مقداردهی اولیش چی کار میکنه . ممنون میشم اگر بگین :) 

</div>

2020-08-11 18:22 UTC, titansarus commented on Phase04/StudentAndScore/StudentAndScore/StudentAndScore/Utility/Query/QueryManager.cs
>              if (numberToTake != -1)
به طور پیشفرض منفی 1 گذاشتیم و اگر منفی 1 باشه، همه داده ها رو بر می گردونه و نیازی نیست که کاربر به طور دقیق مشخص کنه که دقیقا چند تا رو می خواد. اگر چیزی به جز منفی یک باشه، همون تعداد مشخص شده رو بر می گردونه.

2020-08-11 18:25 UTC, mahlashrifi commented on Phase04/StudentAndScore/StudentAndScore/StudentAndScore/Utility/Query/QueryManager.cs
>              if (numberToTake != -1)
<div dir="rtl">

آها . درسته . ممنون .

</div>

2020-08-12 09:01 UTC, mahdimalverdi approved these changes

2020-08-12 10:19 UTC, kimianoorbakhsh approved these changes
خیلی خوب و تمیز بود مثل همیشه، موفق باشین

2020-08-12 10:19 UTC, kimianoorbakhsh commented on Phase04/Learning/library/library/Thing.cs
> +namespace Library
فک کنم این صرفا برای آشنایی با 
csharp
 بود و چون کلا ربطی به بقیه داستان نداره، شاید نباشه بهتره

2020-08-12 11:17 UTC, titansarus commented on Phase04/Learning/library/library/Thing.cs
> +namespace Library
آره این کلا چون داخل داک به یک لینکی که این راهنما و فایل ها داخلش بودن اشاره شده بود، صرفا برای یادگیری قرارش دادیم که باشه و کلا پوشه اش هم جداست و ربطی به بقیه نداره.
ممنون.

2020-08-12 13:23 UTC, merged