Phase05
Star-Academy/Team2-Codes pull request #4
Opened 2020-08-15 08:37 UTC by titansarus

## Phase05

closes https://github.com/Star-Academy/codestar-intern-issues/issues/55

2020-08-15 10:26 UTC, BijanEisapour approved these changes
<p dir='rtl' align='right'>
خیلی عالی بود
<br>
خسته نباشید
</p>

2020-08-15 10:26 UTC, BijanEisapour commented on FullTextSearchCsharp/FullTextSearch/FullTextSearch/Model/InvertedIndex.cs
> +        }
<p dir='rtl' align='right'>
وقتی از foreach استفاده میکنی دیگه نیاز نیست قبلش چک کنی لیست خالی هست یا نه
<br>
به جاش بهتر بود null بودنش چک بشه که Exception پرتاب نکنه
</p>

2020-08-15 10:26 UTC, BijanEisapour commented on FullTextSearchCsharp/FullTextSearch/FullTextSearch/Model/InvertedIndex.cs
> +        }
<p dir='rtl' align='right'>
برای سادگی میشه این شکلی نوشت ...
</p>

```c#
if (!Indexes.ContainsKey(word))
    Indexes.Add(word, new HashSet<string>());
Indexes[word].Add(id);
```

2020-08-15 10:26 UTC, BijanEisapour commented on FullTextSearchCsharp/FullTextSearch/FullTextSearch/Utility/Readers/FileReader.cs
> +        }
<p dir='rtl' align='right'>
نیاز به تعریف متغیر text نیست
<br>
میشه مستقیم نتیجه رو return کرد
</p>

2020-08-15 10:26 UTC, BijanEisapour commented on FullTextSearchCsharp/FullTextSearch/FullTextSearch/Utility/Readers/FileReader.cs
> +            }
<p dir='rtl' align='right'>
اینجا هم نیاز نیست text و document تعریف بشن
<br>
اگه برای Document یه Constructor تعریف کنید کوتاه‌تر میشه
</p>

2020-08-15 13:12 UTC, AlirezaT99 approved these changes

2020-08-16 02:03 UTC, mahdimalverdi commented on FullTextSearchCsharp/FullTextSearch/FullTextSearch/Utility/Readers/FileReader.cs
> +            }
اتفاقا بهتره این اتفاق بیوفته
وقتی اینجوری نوشته میشه دیباگ کردنش به شدت راحت تر میشه

2020-08-16 02:14 UTC, mahdimalverdi requested changes

2020-08-16 02:14 UTC, mahdimalverdi commented on FullTextSearchCsharp/FullTextSearch/FullTextSearch/Model/InvertedIndex.cs
> +                    AddAllWordsOfDocument(document.TokenizedWords.ToList(), document.Id);
چرا ToList شده؟
چرا ورودی تابع IEnumerable نیس؟

2020-08-16 02:14 UTC, mahdimalverdi commented on FullTextSearchCsharp/FullTextSearch/FullTextSearch/QueryProcessors/QueryProcessor.cs
> +            ISet<string> result = new HashSet<string>();
چرا از var استفاده نشده؟

2020-08-16 02:14 UTC, mahdimalverdi commented on FullTextSearchCsharp/FullTextSearch/FullTextSearch/SetOperators/SetOperator.cs
> +            if (queryWords != null && queryWords.Any())
کلا این شرط ختی چک کردن any رو حذف کنید
نال چک بزارید چاش
https://www.thomasclaudiushuber.com/2020/03/12/c-different-ways-to-check-for-null/
اینا رو ببین

2020-08-16 02:14 UTC, mahdimalverdi commented on FullTextSearchCsharp/FullTextSearch/FullTextSearch/SetOperators/SetOperator.cs
> +                    ISet<string> idSet = new HashSet<string> (invertedIndex.Indexes[word]);
invertedIndex.Indexes[word].ToHashSet()
درون System.Linq عه

2020-08-16 02:14 UTC, mahdimalverdi commented on FullTextSearchCsharp/FullTextSearch/FullTextSearch/Utility/Readers/FileReader.cs
> +            foreach (var filePath in AllFilesInFolder)
```CSharp
AllFilesInFolder.Select(f =>
 {
 var text = ReadOneFile(filePath);
return new Document(){Id=filePath, Content = text};
}).ToList()
```

2020-08-16 02:14 UTC, mahdimalverdi commented on FullTextSearchCsharp/FullTextSearch/FullTextSearch/Utility/StringProcessors/InputProcessors/IInputProcessor.cs
> +          abstract void ProcessInput(string input);
چرا اینجا به abstract بودن اشاره کرده؟

2020-08-16 02:14 UTC, mahdimalverdi commented on FullTextSearchCsharp/FullTextSearch/FullTextSearch/Utility/StringProcessors/Tokenizer.cs
> +        private readonly char[] separators =
چرا Const نیست؟

2020-08-16 02:14 UTC, mahdimalverdi commented on FullTextSearchCsharp/FullTextSearch/FullTextSearch/Utility/StringProcessors/Tokenizer.cs
> +            var splitted = content.Split(separators, StringSplitOptions.RemoveEmptyEntries).ToList();
چرا مستقیم ToHashSet نشده؟

2020-08-16 07:43 UTC, titansarus commented on FullTextSearchCsharp/FullTextSearch/FullTextSearch/Model/InvertedIndex.cs
> +                    AddAllWordsOfDocument(document.TokenizedWords.ToList(), document.Id);
اصلاح شد.

2020-08-16 07:43 UTC, titansarus commented on FullTextSearchCsharp/FullTextSearch/FullTextSearch/QueryProcessors/QueryProcessor.cs
> +            ISet<string> result = new HashSet<string>();
اصلاح شد.

2020-08-16 07:43 UTC, titansarus commented on FullTextSearchCsharp/FullTextSearch/FullTextSearch/SetOperators/SetOperator.cs
> +            if (queryWords != null && queryWords.Any())
تقریبا هر جا که این طوری بود و از نظر منطق باعث فیل شدن تست ها نمی شد، اوکی کردم. از جمله همین جا.

2020-08-16 07:44 UTC, titansarus commented on FullTextSearchCsharp/FullTextSearch/FullTextSearch/SetOperators/SetOperator.cs
> +                    ISet<string> idSet = new HashSet<string> (invertedIndex.Indexes[word]);
این اصلا خروجی
Indexes
هش ست بود و اوکی کردمش.

2020-08-16 07:45 UTC, titansarus commented on FullTextSearchCsharp/FullTextSearch/FullTextSearch/Utility/Readers/FileReader.cs
> +            foreach (var filePath in AllFilesInFolder)
اصلاح شد.

2020-08-16 07:47 UTC, titansarus commented on FullTextSearchCsharp/FullTextSearch/FullTextSearch/Utility/StringProcessors/Tokenizer.cs
> +        private readonly char[] separators =
این رو من
const
گذاشتم ولی خطا می داد که آرایه
char
در زمان کامپایل 
const
نیست و نمی شه
const
استفاده کنی و خود ویژوال استودیو و همچنین
Resharper
پیشنهاد میداد که
static readonly
بذارمش.
اینترنت هم سرچ کردم توی استک اورفلو هم نوشته بود که نمیشه
const
گذاشتش
https://stackoverflow.com/questions/5142349/declare-a-const-array

2020-08-16 07:49 UTC, titansarus commented on FullTextSearchCsharp/FullTextSearch/FullTextSearch/Utility/StringProcessors/InputProcessors/IInputProcessor.cs
> +          abstract void ProcessInput(string input);
اوکی شد و حذفش کردم.

2020-08-16 08:13 UTC, titansarus commented on FullTextSearchCsharp/FullTextSearch/FullTextSearch/Model/InvertedIndex.cs
> +        }
اوکی شد.

2020-08-16 08:21 UTC, mahdimalverdi approved these changes

2020-08-16 10:40 UTC, Danyal0096 approved these changes
نکته ای ندیدم اضافه کنم ولی داکیومنتیشنتون خوندن کدتون رو برام جذاب تر میکرد و ازش استفاده خواهم کرد ممنون و موفق باشید

2020-08-16 12:45 UTC, alrz1999 approved these changes

2020-08-16 12:48 UTC, merged