Phase08
Star-Academy/Team2-Codes pull request #6
Opened 2020-08-23 12:04 UTC by titansarus

closes https://github.com/Star-Academy/codestar-intern-issues/issues/83

2020-08-24 08:51 UTC, Danyal0096 reviewed
تو کوئری هندلرتون منطق خواسته شده تو فاز یک اجرا نمیشه یعنی چیزی که شما پیاده کردید ماستش اولویت داره و اند گرفته میشه اون اور ها اصلا انجام نمیشن به نحوی که اگه شما یه کوئری با سه تا کلمه اند بزنید نتیجتون فرقی نمیکنه اگه همون سه کلمه اند رو با دو تا کلمه اور دیگه بزارید یا بهتر بگم این خواسته فاز یک اجرا نمیشه:
"اگر قبل از شروع کلمه کاراکتر + وجود داشته باشد یعنی اگر در یک داکیومنت این کلمه وجود داشت این داکیومنت حتما جزء نتایج باشد."

2020-08-24 09:13 UTC, titansarus commented
> تو کوئری هندلرتون منطق خواسته شده تو فاز یک اجرا نمیشه یعنی چیزی که شما پیاده کردید ماستش اولویت داره و اند گرفته میشه اون اور ها اصلا انجام نمیشن به نحوی که اگه شما یه کوئری با سه تا کلمه اند بزنید نتیجتون فرقی نمیکنه اگه همون سه کلمه اند رو با دو تا کلمه اور دیگه بزارید یا بهتر بگم این خواسته فاز یک اجرا نمیشه:
> "اگر قبل از شروع کلمه کاراکتر + وجود داشته باشد یعنی اگر در یک داکیومنت این کلمه وجود داشت این داکیومنت حتما جزء نتایج باشد."
@Danyal0096 
آره درست میگی. روی یکسری چیزا که تست کرده بودیم، ظاهرا کلمه خیلی خاص بودن که نتیجش درست شده بود. حالا به هر حال الآن اصلاح شد.

2020-08-24 15:13 UTC, AlirezaT99 approved these changes
<div dir="rtl">
بسیار عالی خسته نباشید :)
</div>

2020-08-25 08:47 UTC, MJSahebnasi approved these changes
عالی مثل همیشه
bool query میتونست مختصر تر  و قشنگ تر باشه

2020-08-26 05:13 UTC, alrz1999 requested changes

2020-08-26 05:13 UTC, alrz1999 commented on Phase08/InvertedIndex/Validator/ElasticValidator.cs
> +        public static ValidationResult ValidateElasticResponse(IResponse response)
این تابع طولانی شده فک کنم

2020-08-26 08:15 UTC, titansarus commented on Phase08/InvertedIndex/Validator/ElasticValidator.cs
> +        public static ValidationResult ValidateElasticResponse(IResponse response)
اصلاح شد.

2020-08-26 08:59 UTC, alrz1999 approved these changes

2020-08-26 11:13 UTC, mahdimalverdi requested changes

2020-08-26 11:13 UTC, mahdimalverdi commented on Phase08/InvertedIndex/InvertedIndex/IndexMaker.cs
> +            return indexSettingsDescriptor.Setting("max_ngram_diff", 10);
مقدارهاش کانست بشه

2020-08-26 11:13 UTC, mahdimalverdi commented on Phase08/InvertedIndex/InvertedIndex/Program.cs
> +        private static readonly string IndexName = "document_test";
کانست چرا نیستن؟

2020-08-26 11:13 UTC, mahdimalverdi commented on Phase08/InvertedIndex/InvertedIndex/QueryProcessor/ElasticQueryProcessor.cs
> +            var andStrings = string.Join(" ", andList);
تابعش رو بشکون

2020-08-26 11:13 UTC, mahdimalverdi commented on Phase08/InvertedIndex/InvertedIndex/View/ConsolePrinter.cs
> +            Console.WriteLine("Exception Occured:");
استرینگ ها کانست بشن

2020-08-26 12:26 UTC, titansarus commented on Phase08/InvertedIndex/InvertedIndex/View/ConsolePrinter.cs
> +            Console.WriteLine("Exception Occured:");
اوکی شد.

2020-08-26 12:27 UTC, titansarus commented on Phase08/InvertedIndex/InvertedIndex/QueryProcessor/ElasticQueryProcessor.cs
> +            var andStrings = string.Join(" ", andList);
سازنده کوئری رو به چند قسمت تقسیم کردن از طریق 
extension method
و اوکی شد.

2020-08-26 12:27 UTC, titansarus commented on Phase08/InvertedIndex/InvertedIndex/Program.cs
> +        private static readonly string IndexName = "document_test";
اوکی شد.

2020-08-26 12:27 UTC, titansarus commented on Phase08/InvertedIndex/InvertedIndex/IndexMaker.cs
> +            return indexSettingsDescriptor.Setting("max_ngram_diff", 10);
اوکی شد.

2020-08-26 13:11 UTC, Danyal0096 approved these changes
خیلی خوب بود موفق باشید

2020-08-26 15:04 UTC, mahdimalverdi approved these changes

2020-08-31 09:04 UTC, merged